#!/usr/bin/env python3
"""Render Fortran parameter sources from the shared YAML model config."""

from __future__ import annotations

import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "pyspeedy" / "data" / "model_config.yml"
FORTRAN_OUTPUT_PATH = ROOT / "speedy.f90" / "params.f90"
PYTHON_OUTPUT_PATH = ROOT / "pyspeedy" / "generated_model_config.py"


def load_config(path: Path) -> dict:
    with path.open() as stream:
        filtered = "\n".join(
            line for line in stream.read().splitlines() if not line.lstrip().startswith("#")
        )
        data = json.loads(filtered)
    if not isinstance(data, dict) or "model" not in data:
        raise ValueError(f"Invalid config file: {path}")
    return data


def render_params(model_cfg: dict) -> str:
    bool_literal = ".true." if model_cfg["sppt_on"] else ".false."
    return f"""!> author: Sam Hatfield, Fred Kucharski, Franco Molteni
!  date: 04/07/2019
!  Generated from pyspeedy/data/model_config.yml by scripts/render_model_config.py.
!  Do not edit this file directly.
module params
    use types, only : p

    implicit none

    private
    public trunc, ix, iy, il, kx, nx, mx, ntr, t_levs, aux_dim
    public nsteps, iseasc, nstrad, sppt_on, delt, rob, wil, alph

    ! =========================================================================
    ! Constant parameters
    ! =========================================================================

    ! Model geometry parameters
    integer, parameter :: trunc = {model_cfg["trunc"]}   !! Spectral truncation total wavenumber
    integer, parameter :: ix = {model_cfg["ix"]}      !! Number of longitudes
    integer, parameter :: iy = {model_cfg["iy"]}      !! Number of latitudes in hemisphere
    integer, parameter :: il = 2 * iy    !! Number of latitudes in full sphere
    integer, parameter :: kx = {model_cfg["kx"]}       !! Number of vertical levels
    integer, parameter :: nx = trunc + 2 !! Number of total wavenumbers for spectral storage arrays
    integer, parameter :: mx = trunc + 1 !! Number of zonal wavenumbers for spectral storage arrays
    integer, parameter :: ntr = {model_cfg["ntr"]}      !! Number of tracers (specific humidity is considered a
    !! tracer)

    integer, parameter :: t_levs = {model_cfg["t_levs"]}   !! Number of time levels for the variable.
    integer, parameter :: aux_dim = {model_cfg["aux_dim"]}  !! Auxiliary dimension: 1:land, 2:sea, 3: weighted average

    ! Time stepping parameters
    integer, parameter :: nsteps = {model_cfg["nsteps"]}           !! Number of time steps in one day. Must be an even number?
    real(p), parameter :: delt = 86400.0 / nsteps !! Time step in seconds
    real(p), parameter :: rob = {model_cfg["rob"]}            !! Damping factor in Robert time filter
    real(p), parameter :: wil = {model_cfg["wil"]}            !! Parameter of Williams filter
    real(p), parameter :: alph = {model_cfg["alph"]}            !! Coefficient for semi-implicit computations
    !! 0 -> forward step for gravity wave terms,
    !! 1 -> backward implicit, 0.5 -> centered
    !! implicit

    ! Physics parameters
    integer, parameter :: iseasc = {model_cfg["iseasc"]}        !! Seasonal cycle flag (0=no, 1=yes)
    integer, parameter :: nstrad = {model_cfg["nstrad"]}        !! Period (number of steps) for shortwave radiation
    logical, parameter :: sppt_on = {bool_literal} !! Turn on SPPT?

end module
"""


def render_python(model_cfg: dict) -> str:
    return f'''"""Generated from pyspeedy/data/model_config.yml by scripts/render_model_config.py."""

MODEL_CONFIG = {{
    "trunc": {model_cfg["trunc"]},
    "ix": {model_cfg["ix"]},
    "iy": {model_cfg["iy"]},
    "kx": {model_cfg["kx"]},
    "ntr": {model_cfg["ntr"]},
    "t_levs": {model_cfg["t_levs"]},
    "aux_dim": {model_cfg["aux_dim"]},
    "nsteps": {model_cfg["nsteps"]},
    "iseasc": {model_cfg["iseasc"]},
    "nstrad": {model_cfg["nstrad"]},
    "sppt_on": {bool(model_cfg["sppt_on"])},
    "rob": {model_cfg["rob"]},
    "wil": {model_cfg["wil"]},
    "alph": {model_cfg["alph"]},
}}
'''


def main() -> int:
    config_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else CONFIG_PATH
    config = load_config(config_path)
    fortran_output_path = (
        Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else FORTRAN_OUTPUT_PATH
    )
    python_output_path = (
        Path(sys.argv[3]).resolve() if len(sys.argv) > 3 else PYTHON_OUTPUT_PATH
    )

    fortran_output_path.write_text(render_params(config["model"]))
    python_output_path.write_text(render_python(config["model"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
